services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontier-biz-docs:latest
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.jekyll-cache
      - /usr/src/app/_site
      - /usr/src/app/node_modules  # prevent host node_modules from bleeding in
    environment:
      - JEKYLL_ENV=development
    stdin_open: true
    tty: true